# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Street_add', models.TextField()),
                ('Street_add2', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
