# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='areac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
